language: generic

git:
  depth: 10

matrix:
  include:
    - env: VIM_VERSION=v7.4
    - env: VIM_VERSION=v8.0.0000
    - env: VIM_VERSION=master

addons:
  apt:
    packages:
      - vim

install:
  - bash scripts/install-vim.sh
  - export PATH=$HOME/vim/bin:$PATH

before_script:
  - git clone --depth 1 --branch v1.5.3 --single-branch https://github.com/thinca/vim-themis /tmp/vim-themis

script:
  - uname -a
  - which -a vim
  - vim --cmd version --cmd quit
  - vim --cmd "try | helptags doc/ | catch | cquit | endtry" --cmd quit
  - /tmp/vim-themis/bin/themis --reporter dot
